<a href="https://colab.research.google.com/github/Pavitrakumar45/PythonProgramming/blob/main/Numpy_and_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
 # Import Numpy Library

 import numpy as np


In [6]:
# Array Definition

lst = [10,20,30]

print(type(lst))

<class 'list'>


In [7]:
# Numpy array definition

arr = np.array(lst)

print(type(arr))

<class 'numpy.ndarray'>


In [8]:
# Array Definition

lst1 = [[10,20,30,40,50]]

In [9]:
arry1 = np.array(lst1)

print(type(arry1))

<class 'numpy.ndarray'>


In [10]:
# Checking Shape

print(arry1.shape)

(1, 5)


In [11]:
darray = [[[10,20,30],[60,70,80]]]

array = np.array(darray)
print(array.shape)

(1, 2, 3)


In [12]:
tarray = [[10,20,30],[40,50,60]]

array = np.array(tarray)
print(array.shape)

(2, 3)


In [13]:
# Checking dimension for array

lst =[10,20,40]

array = np.array(lst)

print(array.ndim)

1


In [14]:
lst =[[10,20,40]]

array = np.array(lst)

print(array.ndim)

2


In [15]:
lst =[[[10,20,40]]]

array = np.array(lst)

print(array.ndim)

3


In [16]:
zeros = np.zeros((3,4))      # it idicate 3 rows and 4 columns

print(zeros)
print(zeros.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
12


In [17]:
zeros.T    # Transpose matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
ones = np.array(ones)

'''
whenever we use numpy array ,by default the array contains float value

size = m*n where m = no of rows and n = no of columns

'''
print(ones.sum())
print(ones.sum(axis = 0))    # this will perform operation column wise
print(ones.sum(axis = 1))    # this will perform operation row wise

12.0
[3. 3. 3. 3.]
[4. 4. 4.]


In [19]:
eye = np.eye(4)
print(eye)     # Kernel Filter

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# Aggregate Function

lst = [10,20,30,40]

a = np.array(lst)

print(a.sum())
print(a.max())
print(a.min())
print(a.var())
print(a.std())

100
40
10
125.0
11.180339887498949


In [25]:
array1 = np.array([[10,20,30],[40,50,60]])
array2 = np.array([[10,20,30],[40,50,60]])

array3 = array1 + array2
print(array3)

[[ 20  40  60]
 [ 80 100 120]]


In [26]:
a = array3.sum(axis = 0)
b = array3.sum(axis = 1)
print(a)
print(b)

[100 140 180]
[120 300]


In [27]:
a = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[100,200,300,400,500,600],[1000,2000,3000,4000,5000,6000]])

print(a[:,:])

[[   1    2    3    4    5    6]
 [  10   20   30   40   50   60]
 [ 100  200  300  400  500  600]
 [1000 2000 3000 4000 5000 6000]]


In [28]:
print(a[1:2,:2])

[[10 20]]


In [35]:
print(a[2:,3:5])

[[ 400  500]
 [4000 5000]]


In [36]:
print(a[2:,4:])

[[ 500  600]
 [5000 6000]]


In [37]:
print(a[:1,2:4])

[[3 4]]


In [41]:
# Question

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,0,0],[0,2,0],[0,0,2]]).T
c = a*b

In [42]:
print(c.ndim)
print(c.size)
print(c.shape)
print(c)


2
9
(3, 3)
[[ 2  0  0]
 [ 0 10  0]
 [ 0  0 18]]


In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,0,0],[0,2,0],[0,0,2],[1,2,3]]).T
c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 